### ISSUE TITLE
[Feature Request] Host/Motherboard/Device model name

### ISSUE THREAD

**Issue by LukeHuckman** [TheDarkBug/uwufetch#102]
Another system information that seems like it might be worth adding. I don't exactly know how it would be implemented for different platforms though, but I think it's doable.

**Comment by dqnk** [comment]
I don't know if this is really important, because other popular fetch tools (neofetch) don't show it.

**Comment by LukeHuckman** [comment]
Neofetch does actually. It's highlighted in the screenshot here:
![image](https://user-images.githubusercontent.com/45264354/121780229-03aa5f80-cbd2-11eb-9e89-9f80124d72f0.png)

**Comment by TheDarkBug** [comment]
To get this info, `uwufetch` could read `/sys/devices/virtual/dmi/id/product_name` to get the product name, or `/sys/devices/virtual/dmi/id/board_name` to get motherboard name and product name:

![Schermata da 2021-06-12 17-53-38](https://user-images.githubusercontent.com/41623496/121781920-50c50c00-cba7-11eb-85fc-076fe126498c.png)

**Comment by LukeHuckman** [comment]
Is the path the same for Android and non-Linux based OSes?

**Comment by TheDarkBug** [comment]
> Is the path the same for Android and non-Linux based OSes?

On Android this files do not exist, so `getprop ro.product.model` is the only way to get it.
On Mac os and other bsd systems `/sys/devices/virtual/dmi/id/*` should exist, but I am not sure.

> Also, there are some cases where one of those paths is not used, i.e. the motherboard vendor left it empty with a placeholder value like this:

In that case the other file will be read.

I'll work on it later.

**Comment by TheDarkBug** [comment]
In the last update I used `/sys/devices/virtual/dmi/id/product_name`, that gives the best result on my desktop and on my laptop, and also works in most of my vms.
