### ISSUE TITLE
Uwu'fy kernel name

### ISSUE THREAD

**Issue by SupinePandora43** [TheDarkBug/uwufetch#103]
![image](https://user-images.githubusercontent.com/36124472/122568438-2d94d380-d063-11eb-8d59-96acea049af9.png)
`Linux 5.10.42-1-MANJARO` to `Linux 5.10.42-1-MYANJAWO`

**Comment by TheDarkBug** [comment]
In uwufetch the `owos` name is fully replaced, uwufing the `kewnel` version is more complex: it is not only one string which is common for every system, it is made of 'Linux' + linux version number + other things depending on what distro are you on and if you are using a custom kernel.
There are many solutions:

**Comment by TheDarkBug** [comment]
Closed by error

**Comment by LukeHuckman** [comment]
This would work if the system is using the distro-provided kernel I guess since each distro has its own kernel version convention. We can just use that to determine which part of the version info to uwu-fy. I'm not sure how this would work for custom kernels though.

**Comment by TheDarkBug** [comment]
Yes, we could do it aside the distro detection, and if a custom kernel is detected, it will use its (uwufied) name.
