### ISSUE TITLE
Linux specific include?

### ISSUE THREAD

**Issue by KenwoodFox** [TheDarkBug/uwufetch#104]
Build fails on FreeBSD 12
```
# gmake build
cc -O3 -o uwufetch uwufetch.c
uwufetch.c:26:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>
         ^~~~~~~~~~~~~~~
1 error generated.
gmake: *** [Makefile:18: build] Error 1
```

**Comment by TheDarkBug** [comment]
Actually on the freebsd website there is a [man page](https://www.freebsd.org/cgi/man.cgi?query=sysinfo&sektion=3&manpath=FreeBSD+13.0-RELEASE+and+Ports), so the file should exist.
What compiler are you using?

**Comment by TheDarkBug** [comment]
It's been a month without reply, I think I can close this. I tried to build `uwufetch` in a VM with freebsd and there wasn't this problem.

**Comment by sech1p** [comment]
It's looks like `sysinfo.h` is a GNU libc header, however, *BSD distributions uses BSD libc which doesn't have it 👀

**Comment by TheDarkBug** [comment]
So installing glibc on *BSD should fix it. I can't remember if on my VM I installed it or not, I'm gonna try again tomorrow.

**Comment by sech1p** [comment]
> So installing glibc on *BSD should fix it

I think we should make uwufetch on BSD distributions native (without using GNU libc), on macOS works perfect without using GNU so BSD should not using GNU too

**Comment by TheDarkBug** [comment]
Yes, you are right, I'm trying to port it to *BSD libc

**Comment by TheDarkBug** [comment]
FreeBSD port is almost done, now only `HOWOST` does not work.
