### ISSUE TITLE
issues with saving output to file

### ISSUE THREAD

**Issue by Joshix-1** [TheDarkBug/uwufetch#108]
![2021-07-21_13-42](https://user-images.githubusercontent.com/57299889/126483273-e078af99-f628-421b-88b6-e6c5296fc11b.png)
When I try saving the output of uwufetch to a file some information is missing.

![2021-07-21_13-45](https://user-images.githubusercontent.com/57299889/126483541-a519cd64-0fcf-4551-84ee-ccc3ab56f914.png)
Another problem is that the ascii art is above the information it would be great to have it on the left like it gets displayed.

uwufetch-version: 1.4-1 (AUR)
Terminal: Alacritty

Another thing: for some reason uwufetch sometimes prints the text starting on the line of the command. that's why I added the "echo" thing

**Comment by dqnk** [comment]
the missing rows seem to appear because of the function `void truncate_name(char *name)`

**Comment by dqnk** [comment]
> Another problem is that the ascii art is above the information it would be great to have it on the left like it gets display
I don't think that should be considered an issue, it only happens because of formatting. in the end when you use `cat`, the information is displayed correctly.

**Comment by dqnk** [comment]
>Another thing: for some reason uwufetch sometimes prints the text starting on the line of the command.

This has never happened to me (kitty terminal + fish shell). Could you post a screenshot perhaps?
