### ISSUE TITLE
uwufetch always shows at top

### ISSUE THREAD

**Issue by Guaxinim5573** [TheDarkBug/uwufetch#11]
uwufetch always shows at the top of the terminal instead of just print all information normaly.

Example:
Just some `echo` and then `uwufetch`.
![image](https://user-images.githubusercontent.com/49736632/110222409-aefb9800-7eb0-11eb-9119-8540c4f8e2d0.png)
Some `ls`, one `neofetch` then `uwufetch`.
![image](https://user-images.githubusercontent.com/49736632/110222444-01d54f80-7eb1-11eb-9a13-6890e62236ab.png)

**Comment by TheDarkBug** [comment]
Thats because I forgot to set the cursor in the relative position (the fix should be pretty easy). Thanks for letting me notice.
