### ISSUE TITLE
uwufetch displaying the content one row to high (sometimes)

### ISSUE THREAD

**Issue by Joshix-1** [TheDarkBug/uwufetch#111]
![2021-07-21_20-52](https://user-images.githubusercontent.com/57299889/126543893-3b87439f-bd6f-4a33-b114-c1e642059a12.png)

I could see this behavior with alacritty and kitty

**Comment by dqnk** [comment]
For now I suggest you install `viu` and add `image="/usr/lib/uwufetch/arch.png"` to your `.config/uwufetch/config` file. The issue only seems to appear if you are using ascii art.

**Comment by Joshix-1** [comment]
It also happened when catting the output of the file.
After I edited the file to the following it worked: (note the new line and the spaces infront of the ascii logo)
```
[1E[8C[34m
        /\
       /  \
      /\   \
     / > ω <\
    /   __   \
   / __|  |__-\
  /_-''    ''-_\

[9A[18C[0m[1mjosh@box
[18C[0m[1mOWOS        [0mNyarch Linuwu
[18C[0m[1mHOWOST      [0m1.0
[18C[0m[1mKEWNEL      [0mLinuwu 5.13.0-173-tkg-pds x86_64             
[18C[0m[1mCPUWU       [0mAMD Ryzen 5 2400G with Radeon Vega Graphics
[18C[0m[1mGPUWU       [0mRaven Ridge Radeon Vega Series / Radeon Vega Mobile Series
[18C[0m[1mWAM         [0m16873 MiB/30035 MiB
[18C[0m[1mRESOWUTION[0m  1920x1080
[18C[0m[1mSHEWW       [0m/bin/zsh
[18C[0m[1mPKGS        [0m[0m2092: 2092 (pacman)
[18C[0m[1mUWUPTIME    [0m19d, 23h, 19m
[18C[1m[30m▇▇[31m▇▇[32m▇▇[33m▇▇[34m▇▇[0;35m▇▇[36m▇▇[37m▇▇[0m
```
