### ISSUE TITLE
Move all ascii arts to own file 

### ISSUE THREAD

**Issue by Joshix-1** [TheDarkBug/uwufetch#114]
1. This would allow easier modification
2. Make it easier to specify path to own images

**Comment by Guaxinim5573** [comment]
I agree.

Just like images, we could store each ascii art in a file in `res/`.
Maybe we could store them in simple text files, read and then write them to stdout. Should be an easy implementation.
The only problem is working with colors, we could:
- Have just one fixed color for ascii art.
- Have a place holder (like {COLOR_NAME}) for each color in the file, then replacing them with actual code.
I'll try the second option.

**Comment by Joshix-1** [comment]
with place_holders it would be easier to read. All the %s are really confusing.
