### ISSUE TITLE
Rewrite get_info() bash commands into shell-compatible commands

### ISSUE THREAD

**Issue by kugiyasan** [TheDarkBug/uwufetch#12]
Shell: zsh
OS: ubuntu on wsl2

When running `uwufetch`, I'm getting some error:
`sh: 1: Syntax error: redirection unexpected`
`sh: 1: Syntax error: redirection unexpected`

If I comment out the 2 `popen()` lines in `get_info()`, uwufetch runs without error (although the OS and the CPU aren't displayed).
I tried running both commands in bash and zsh, and it worked without problem.
Pasting those commands into sh indeed raises the same errors as when I run uwufetch, so it seems like `popen()` is calling sh for me, whatever the original shell I was using.

**Comment by zcake3000** [comment]
I hame same issue on debian inside chroot.
Here is screenshot :
![2021-03-07_10-59](https://user-images.githubusercontent.com/70055899/110227537-5bcb2900-7f34-11eb-847a-5b13599df1d3.png)

**Comment by TheDarkBug** [comment]
Solved by #13
