### ISSUE TITLE
Build cp: no such file or directory

### ISSUE THREAD

**Issue by soshimee** [TheDarkBug/uwufetch#125]
While building, it fails with error:
`cp: cannot create regular file '/home/(username)/.cache/yay/uwufetch-git/pkg/uwufetch-git/usr/bin/uwufetch': no such file or directory`
even if I create it myself, it gets deleted and fails.

**Comment by TheDarkBug** [comment]
I just pushed an update on the aur that should fix

**Comment by TheDarkBug** [comment]
Fixed with [1.6](https://github.com/TheDarkBug/uwufetch/releases/tag/1.6)
