### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by L-Developer** [TheDarkBug/uwufetch#132]
When running running make I keep getting the same error
```
cc -O3 -o uwufetch uwufetch.c
make: cc: No such file or directory
make: *** [Makefile:25: build] Error 127
```
this goes for ```make build``` and ```sudo make install```.
My pc is running artix.

**Comment by TheDarkBug** [comment]
Do you have a compiler installed (like `gcc` or `clang`)?

**Comment by L-Developer** [comment]
I may be a dumbass
