### ISSUE TITLE
xerolinux support

### ISSUE THREAD

**Issue by egor4ka** [TheDarkBug/uwufetch#135]
could you please add xerolinux support? xuwulinux for example

**Comment by TheDarkBug** [comment]
Where can I find an iso for this distro?

**Comment by sech1p** [comment]
> Where can I find an iso for this distro?

it's probably it: https://xldb.techxero.com

**Comment by TheDarkBug** [comment]
Oh sorry I didn't notice it

**Comment by egor4ka** [comment]
so are you going to add it?

**Comment by egor4ka** [comment]
> Where can I find an iso for this distro?

its on sourceforge

**Comment by egor4ka** [comment]
xuwulinux!

**Comment by TheDarkBug** [comment]
> so are you going to add it?

Of course, I am waiting for the download to end

**Comment by egor4ka** [comment]
> > Where can I find an iso for this distro?
> 
> it's probably it: https://xldb.techxero.com

this is the distro's website, but the iso is on sourceforge

**Comment by egor4ka** [comment]
> > so are you going to add it?
> 
> Of course, I am waiting for the download to end

oh ok lol

**Comment by egor4ka** [comment]
https://reddit.com/r/uwufetch/?utm_medium=android_app&utm_source=share i made an uwufetch subreddit

**Comment by TheDarkBug** [comment]
Xerolinux was added to the supported distros

**Comment by egor4ka** [comment]
yay
