### ISSUE TITLE
Can't build on MacOwOs

### ISSUE THREAD

**Issue by KripC2160** [TheDarkBug/uwufetch#147]
I tried to install uwufetch on MacOwOs  however when I try to make build, it shows this error.

`cc -O3 -o uwufetch uwufetch.c
uwufetch.c:559:2: error: implicit declaration of function 'sysinfo' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        sysinfo(&sys); // to get uptime
        ^
uwufetch.c:559:11: error: use of undeclared identifier 'sys'
        sysinfo(&sys); // to get uptime
                 ^
`

I am currently using Macbook Air with Apple M1 chip and MacOwOs Big Sur version 11.3.1

**Comment by elegantShock2258** [comment]
you did  `make install` right?
what does `make debug` show?

**Comment by KripC2160** [comment]
for make install (I didn't try that since it was process after make build) the result was this 
`mkdir -p /usr/local/bin /usr/local/lib/uwufetch /usr/local/share/man/man1
cp uwufetch /usr/local/bin/uwufetch
cp: uwufetch: No such file or directory
make: *** [install] Error 1`

**Comment by TheDarkBug** [comment]
Since I have no way to test this on a mac, could you try to build the _mac_os_testing_ branch?

**Comment by elegantShock2258** [comment]
great! nor do `sudo make install` and if it works , you should close the issue!

**Comment by KripC2160** [comment]
alright thank you for you help!
