### ISSUE TITLE
Moving image files in res/ to /usr/lib instead for better compatibility with package managers

### ISSUE THREAD

**Issue by LukeHuckman** [TheDarkBug/uwufetch#15]
This is only a suggestion, because I'm writing a PKGBUILD for uwufetch and the Arch build system restricts packages from writing to the home folder at install time. This is probably true for other package managers if someone were to create a package for this as well since it would be problematic if resource files were to be available to only the user that installed it while the binary is installed globally.

**Comment by TheDarkBug** [comment]
Thank you, I was thinking to publish uwufetch, but I didn't know how. Yes, I can do it, but I would need to create a folder `/usr/lib/uwufetch` to put all images in, does it work if the folder has a custom name?

**Comment by LukeHuckman** [comment]
Yeah, I think `/usr/lib/uwufetch` would work.
Btw, I've already published what I could work on so far to the AUR.
Here's the link: https://aur.archlinux.org/packages/uwufetch-git/
From the PKGBUILD:
```
package() {
	cd "$srcdir/${pkgname}"
	install -D "uwufetch" "$pkgdir/usr/bin/uwufetch"
}
```
I think I can add `install` commands to move the pictures there, but it also needs to be referred to in the source for it to work of course.

**Comment by TheDarkBug** [comment]
I updated the source, so the images are in `/usr/lib/uwufetch/`. Should I make releases or something to help?

**Comment by LukeHuckman** [comment]
I've updated the PKGBUILD with the new pictures directory and it works nicely.
![image](https://user-images.githubusercontent.com/45264354/110247583-e8fb9580-7fa7-11eb-8f46-25ac9955668f.png)
And regarding releases, I'll probably have to create a separate PKGBUILD for that. If you have an AUR account, I can give you access to co-maintain I guess

**Comment by TheDarkBug** [comment]
That's nice!

>If you have an AUR account...

Yes I have an AUR account, my username is `TheDarkBug` just like here oh github. Maybe in the future I'll publish releases.
