### ISSUE TITLE
Make the dependencies more fleshed out.

### ISSUE THREAD

**Issue by UwUnyaa** [TheDarkBug/uwufetch#153]
I've noticed in someone else's uwufetch that the resolution can be reported. Because the information is not listed anywhere, I've had to go through the source code to figure out how it's picked up, and found that it uses the `xwininfo` utility. In my case (Arch), the package that provides this utility is [`xorg-xwininfo`](https://archlinux.org/packages/extra/x86_64/xorg-xwininfo/).

I think it would make sense to document all dependencies of this utility in the README, and propagate them as optional dependencies to packages, including the AUR one. I'd have to spend more time to figure all of these out, and I don't have easy access to macOS to test on that platform among others.

**Comment by TheDarkBug** [comment]
Dependancies are already in the readme, but sometimes when someone adds a feature, forgets to add new dependancies to the list. After listing all the depends, I will write a better guide for pull requests to [CONTRIBUTING.md](https://github.com/TheDarkBug/uwufetch/blob/main/CONTRIBUTING.md)
