### ISSUE TITLE
[BUG] Segmentation fault on raspberry pi 3 B+

### ISSUE THREAD

**Issue by 4zv4l** [TheDarkBug/uwufetch#154]
I get a segfault after compiling the code from git and also from yay
`(gdb) r
Starting program: /home/azz/git/uwufetch/uwufetch
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x76e9927c in fclose@@GLIBC_2.4 () from /usr/lib/libc.so.6
(gdb)`
I didn't more for now to see what cause the seg fault but it used to work before
![image](https://user-images.githubusercontent.com/46655455/139504038-6710f3c0-92dc-4500-94d2-34a28c59441b.png)

**Comment by 4zv4l** [comment]
ok I found the bug
in `get_info( )`
the check for `*host_model_info`
it always fclose( ) the file even if couldn't be opened with the first or second way so ofc it segfault.

**Comment by 4zv4l** [comment]
![image](https://user-images.githubusercontent.com/46655455/139506227-14fdc21f-4845-4a50-ad27-6d6e347cca1f.png)

I could remove the bug like this

**Comment by TheDarkBug** [comment]
Could you send a PR? If you can't I'll update the code tomorrow.

**Comment by 4zv4l** [comment]
> Could you send a PR? If you can't I'll update the code tomorrow.

I tried but it says I don't have the right to do a pull request (I'm quiet new to those things so I tried to create a branch locally, do the change and push it but it says I don't have the right) so if you can tell me which way I need to take to do a pull request I would do it with pleasure

**Comment by TheDarkBug** [comment]
Actually I don't know, I have never sent a pull request, sorry.
