### ISSUE TITLE
Nyartix copyholder is complaining about the copyright page.

### ISSUE THREAD

**Issue by exkc** [TheDarkBug/uwufetch#155]
Hi ! i am Nyartix copyholder. I licenced it under  DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE in 2021-08-22 .(prove : https://www.reddit.com/r/linuxmasterrace/comments/ly6wd1/nyartix/gpxdwc2/?context=3) but in your copyright page , it say Nyartix logo is no LICENSE which is wrong.

 btw u/akzcake  changed his reddit  account to u/exxxxkc

**Comment by TheDarkBug** [comment]
Oh I'm sorry, I'll update as soon as I can

**Comment by exkc** [comment]
Thank :)

Btw i am also the creator of it.
