### ISSUE TITLE
AmogOS arm edition not being detected correctly

### ISSUE THREAD

**Issue by mobilegmYT** [TheDarkBug/uwufetch#167]
On the RPI edition of AmogOS, uwufetch detects the OS as Raspberry Pi OS and not AmogOS (presumably because of the fix it uses with plymouth)

**Comment by mobilegmYT** [comment]
(also about the plymouth patch, the next release will have `amogos` set to the `ID` in /etc/os-release in the upcoming version)

**Comment by TheDarkBug** [comment]
> (also about the plymouth patch, the next release will have `amogos` set to the `ID` in /etc/os-release in the upcoming version)

That's nice to know, finally the lines from [753](https://github.com/TheDarkBug/uwufetch/blob/main/uwufetch.c#L753) to [762](https://github.com/TheDarkBug/uwufetch/blob/main/uwufetch.c#L762) will be removed!
