### ISSUE TITLE
openSUSE Tumbleweed support not reliable

### ISSUE THREAD

**Issue by alexander-m-pusch** [TheDarkBug/uwufetch#168]
openSUSE Tumbleweed is not listed as a supported distribution. However I can see in uwufetch.c that KERNEL_TO_UWU and STRING_TO_UWU opensuse-tumbleweed is shown as supported, yet running uwufetch on opensuse-tumbleweed returns "unknown OS".

**Comment by TheDarkBug** [comment]
That's because "opensuse-leap.txt" exists (res/ascii/) bit there is no tumbleweed file
