### ISSUE TITLE
Another issue with UwUfetch on macOS

### ISSUE THREAD

**Issue by Lucz0xxZ** [TheDarkBug/uwufetch#172]
Basically, Uwufetch detects macOS as iOS and it doesn't display number of packages. SS below:

<img width="368" alt="Screenshot 2021-12-06 at 12 13 32" src="https://user-images.githubusercontent.com/76839900/144836511-258186fb-e576-4845-a471-8c49ff20aae5.png">

**Comment by Lucz0xxZ** [comment]
didn't work..

**Comment by Lucz0xxZ** [comment]
it displays the packages count but the os is still iOS

**Comment by TheDarkBug** [comment]
I replaced `TARGET_OS_IPHONE` with `__IPHONE__` so it will not be defined by default. Should work (I hope).

**Comment by Lucz0xxZ** [comment]
It works now. Thanks for resolving this issue!
