### ISSUE TITLE
PR #176 issue

### ISSUE THREAD

**Issue by dqnk** [TheDarkBug/uwufetch#180]
PR #176 is pointless and confusing, we have a flag for disabling model info, called `host`. Revert it and delete those lines or just explain that adding `host=false` in `.config/uwufetch/config` fixes the issue instead of commenting out those lines. 
I tried to open a pull request to revert it, but it seems that the content has been changed since.

**Comment by TheDarkBug** [comment]
You're right. I don't remember why I accepted the pr without modifying the readme changes.
I am closing this because I acceptet #181
