### ISSUE TITLE
More commit #176 issues

### ISSUE THREAD

**Issue by dqnk** [TheDarkBug/uwufetch#182]
What exactly do the 3 commented lines at 980 have to do with OEM information and why are they commented out? Isn't this just information for android?

```
//model_fp = popen("getprop ro.product.model", "r");
//while (fgets(buffer, sizeof(buffer), model_fp) && !sscanf(buffer, "%[^\n]", user_info.model))
//	;
```

**Comment by TheDarkBug** [comment]
Yes it is for android (and here's why MOWODEL on android wasn't working)
