### ISSUE TITLE
bug: host section broken

### ISSUE THREAD

**Issue by luczoxz** [TheDarkBug/uwufetch#185]
As you can see on the image below, uwufetch is not displaying host properly ;-;
![image](https://user-images.githubusercontent.com/76839900/151346695-10ea5688-305d-4d15-8013-d5198eae0b11.png)

**Comment by TheDarkBug** [comment]
Wait did you update `uwufetch`? Now that info is called "MOWODEL" and has a nice algorithm to choose what to print

**Comment by TheDarkBug** [comment]
Closed due to inactivity

**Comment by luczoxz** [comment]
@TheDarkBug I'm sorry for not responding. This seems like an issue with my laptop only. I can't test it now, so even if that was an issue that happens with other devices, it's unfixable until someone other than me has that problem too.

**Comment by TheDarkBug** [comment]
The hosts section had lots of issues ([102](https://github.com/TheDarkBug/uwufetch/issues/102), [154](https://github.com/TheDarkBug/uwufetch/issues/154), [180](https://github.com/TheDarkBug/uwufetch/issues/180)) and pull requests ([119](https://github.com/TheDarkBug/uwufetch/pull/119), [146](https://github.com/TheDarkBug/uwufetch/pull/146) , [159](https://github.com/TheDarkBug/uwufetch/pull/159), [174](https://github.com/TheDarkBug/uwufetch/pull/174), [176](https://github.com/TheDarkBug/uwufetch/pull/176), [181](https://github.com/TheDarkBug/uwufetch/pull/181 ), [182](https://github.com/TheDarkBug/uwufetch/pull/182 )) in the past, but now it's pretty unlikely that your issue still exists (maybe just a different issue), as the algorithm to get this info changed more than one time in the last 2/3 months (host info name [also changed](https://github.com/TheDarkBug/uwufetch/pull/174#issuecomment-997292337 )) .
If you will test again on your laptop, let me know if the issue persists.
