### ISSUE TITLE
void linux isn't detected

### ISSUE THREAD

**Issue by wael444** [TheDarkBug/uwufetch#188]
bottom text
```
$ cat /etc/os-release
NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"
```

**Comment by TheDarkBug** [comment]
Should be fixed now

**Comment by wael444** [comment]
it doesn't.

**Comment by TheDarkBug** [comment]
Ok right now I'm busy, I'll fix it later.
Meanwhile, are you sure that cache is disabled?

**Comment by wael444** [comment]
> Meanwhile, are you sure that cache is disabled?

it doesn't get created, well, it isn't in ~/.cache. or no file in / matches keyword 'uwufetch'

**Comment by TheDarkBug** [comment]
I copied this
> ```
> $ cat /etc/os-release
> NAME="void"
> ID="void"
> DISTRIB_ID="void"
> PRETTY_NAME="void"
> ```

in my `/etc/os-release` and tested [ad522fb](https://github.com/TheDarkBug/uwufetch/commit/ad522fbffb612ce842abe8d7aa7ed130a442c9cb) and it works, so I don't really know what's the problem on your system.

Try to apply [this diff file](https://github.com/TheDarkBug/uwufetch/files/8008385/debug.txt) with `git apply debug.txt`, then send the output of `make debug`. To remove the patch, run `git reset --hard HEAD && git pull`

**Comment by wael444** [comment]
```
cc -Wall -Wextra -g -pthread -o uwufetch uwufetch.c
./uwufetch

void"
```

**Comment by TheDarkBug** [comment]
Maybe you didn't update, run `git reset --hard HEAD && git pull` and try to run it again (without applying the patch)

**Comment by wael444** [comment]
it works now, thanks.
