### ISSUE TITLE
No config file being generated

### ISSUE THREAD

**Issue by Thubs** [TheDarkBug/uwufetch#190]
Using manual install I have ran both the make build and the make install commands and there was no config file generated in the .config directory, I am using Pop!_os.

**Comment by TheDarkBug** [comment]
I'm sorry, I forgot to answer. Anyways.
I think that a (default) global configuration (in `/etc/uwufetch/config`) would be a nice addition, even as an example of what you can toggle with that file. The `~/.config/uwufetch/config` file would still need to be created manually (or by copying the default config)

**Comment by TheDarkBug** [comment]
I added a default config (in `/etc/uwufetch/config`): acd9662a30cc5a363b4e77ad03cbddaeaec963c9

**Comment by Thubs** [comment]
Awesome thanks
