### ISSUE TITLE
[BUG] macOS ascii and package manager indentation broken

### ISSUE THREAD

**Issue by axoteric** [TheDarkBug/uwufetch#191]
The ascii art for macOS is incomplete and missing a line. It appears that someone tried to remedy this by improperly adding another line with two W's in uwufetch.c, which has the effect of breaking indentation instead. See below:
<img width="547" alt="broken" src="https://user-images.githubusercontent.com/96516487/157533153-7c0fb4f8-5fcc-40f4-8819-7de0d82b6ce5.png">

**Comment by TheDarkBug** [comment]
Fixed with #192
