### ISSUE TITLE
gpu=false disables showing dedicated and integrated GPUs

### ISSUE THREAD

**Issue by greembow** [TheDarkBug/uwufetch#195]
If I use `gpu=false` in the config file, then it disabled showing all gpu fields. My laptop has a dedicated quadrowo and i only want that to appear in the uwufetch output. Thanks greatly appreciated!

Idea: Have the config value be either false (disables both), or dedicated (only shows the dedicated card)

**Comment by TheDarkBug** [comment]
I'm sorry, I totally forgot about this issue.

I think that using numbers to show a gpu would be a better thing to do:
- If a computer has two dgpus and an igpu, I can selectively enable only one (or even more) gpu
- It's pretty complicated to get the gpu type, also it could fail

I'm working on that btw.
