### ISSUE TITLE
sys/sysinfo.h not found on openbsd

### ISSUE THREAD

**Issue by hellisabove** [TheDarkBug/uwufetch#198]
uwufetch.c:38:13: fatal error: 'sys/sysinfo.h' file not found
                        #include <sys/sysinfo.h>
                                 ^~~~~~~~~~~~~~~

**Comment by TheDarkBug** [comment]
I'm sorry for my late answer, but I'm a little busy with my exams in this period (fixing issues might take a long time).
Just like for freebsd (#104) `sys/sysinfo.h` does not exist. And we need again to reimplement some functions to get it working. As soon as I can, I'll install openbsd on some kind of virtual machine and work on the port there.
