### ISSUE TITLE
Can not compile on macOS 13 Ventura

### ISSUE THREAD

**Issue by haunt98** [TheDarkBug/uwufetch#205]
I use macOS 13 Ventura, after pull latest commit, can not build.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/5424272/198092490-a921e3c9-e572-4220-a51c-dc3e18653f36.png">

Look like `uptime_apple()` is missing

```sh
uwufetch.c:520:22: error: implicit declaration of function 'uptime_apple' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        user_info->uptime = uptime_apple();
```

**Comment by TheDarkBug** [comment]
Right now I do not have a mac to try the fixes, so could you try to switch to this new branch and compile? (`git checkout 205-macos-fix`)

**Comment by haunt98** [comment]
@TheDarkBug Looks like you fix it! Thanks!

<img width="720" alt="image" src="https://user-images.githubusercontent.com/5424272/198502630-8cf7da1e-789c-44a9-a7aa-2281084cc788.png">

<img width="720" alt="image" src="https://user-images.githubusercontent.com/5424272/198502723-aa713249-1477-4e9d-839b-883dde588ae5.png">
