### ISSUE TITLE
[BUG] weird ram digits

### ISSUE THREAD

**Issue by Radiicall** [TheDarkBug/uwufetch#219]
![image](https://user-images.githubusercontent.com/66682497/219343504-07822f76-7a9f-4810-9c90-2585311a6728.png)

I dont know if i can reproduce this..

**Comment by TheDarkBug** [comment]
Could you send a `uwufetch -v`?

**Comment by Radiicall** [comment]
Nope sorry i cant, managed to break my install and i cant get it back...

**Comment by TheDarkBug** [comment]
So it's fixed?

**Comment by Radiicall** [comment]
Yeah...
