### ISSUE TITLE
Check if viu is installed before attempting uwufetch -i

### ISSUE THREAD

**Issue by LukeHuckman** [TheDarkBug/uwufetch#22]
Right now, when trying to use `uwufetch -i` without viu installed this will show up:
![image](https://user-images.githubusercontent.com/45264354/110443293-b8764180-80f6-11eb-9359-de58874e4138.png)
My suggestion is to implement a checking mechanism to see if `viu` is installed in the system (maybe `whereis viu`?) and print a proper error message if it's not installed and/or fall back to ascii.

**Comment by TheDarkBug** [comment]
I should write some kind of check, I already tried with `where` and `which`, but they work only on zsh. I thought to include a check in the makefile, just as a warning, then I could take all the necessary time to write some error handling.

**Comment by TheDarkBug** [comment]
Solved with last commit (and with #23)
