### ISSUE TITLE
no arm/android support

### ISSUE THREAD

**Issue by cookies5219** [TheDarkBug/uwufetch#229]
trying to compile it in termux and it gives me "make: ar: No such file or directory"
![image](https://github.com/TheDarkBug/uwufetch/assets/79637866/8f33fb6a-3dad-4f2d-bd4f-1d776d24f20f)

**Comment by TheDarkBug** [comment]
The `ar` command is part of the package `binutils`. Before you build in termux, you have to run `pkg install binutils` and maybe other commands.
