### ISSUE TITLE
[BUG] Some information was wrong

### ISSUE THREAD

**Issue by dontknowhy** [TheDarkBug/uwufetch#234]
**Describe the bug**
I compiled this cute stuff and i found that I made a wrong decision.
Almost everything she has been displayed was wrong
**To Reproduce**
![Screenshot_20230617_213448](https://github.com/TheDarkBug/uwufetch/assets/85813508/d5e60306-f6c0-4aba-8665-f3fc97a8d5b9)
Yes it's almost (
**Expected behavior**
Like the second uwufetch.It's the old version
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Android12
 - Browser [e.g. chrome, safari] WHAT? Edge Canary for Android?
 - Version [e.g. 22] 11.6

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] BRT-W09
 - OS: [e.g. iOS8.1] iOS (nope) MagicOS 6.1
 - Browser [e.g. stock browser, safari] Edge Canary
 - Version [e.g. 22] 11.6

**Additional context**
The neofetch one is correct.

**Are you already working on this bug?**
I'm lazy.

**Comment by dontknowhy** [comment]
My tablet:It's really hot here 🥵

**Comment by TheDarkBug** [comment]
I'm rewriting `fetch.c` (the part of `uwufetch` that gathers info from the system), in the new version everything should be fine.
I will not close the issue as when [libfetch-rewrite](https://github.com/TheDarkBug/uwufetch/tree/libfetch-rewrite) will be merged in main I will need your feedback.

**Comment by TheDarkBug** [comment]
I wrote new code to get cpu name on android, could you test it by:
- `git pull`
- `git checkout libfetch-rewrite`
- `make clean all run`

**Comment by dontknowhy** [comment]
> I wrote new code to get cpu name on android, could you test it by:
> 
> * `git pull`
> * `git checkout libfetch-rewrite`
> * `make clean all run`

Now the CPU part works fine,but model detection is broken
![Screenshot_20231124_195533](https://github.com/TheDarkBug/uwufetch/assets/85813508/71be64c1-8b52-4c61-8ca7-e9f967485f11)

**Comment by TheDarkBug** [comment]
Should be fixed by [25feae2](https://github.com/TheDarkBug/uwufetch/commit/25feae2c5206a4fb3c86ed30b681778552c149f3) (in the [development](https://github.com/TheDarkBug/uwufetch/tree/development) branch)

**Comment by dontknowhy** [comment]
![Screenshot_20231210_111129](https://github.com/TheDarkBug/uwufetch/assets/85813508/f1a8f345-2b08-43c4-9a7e-51712679e7c0)
It works!(maybe...)
