### ISSUE TITLE
[FEATURE-REQUEST Fastuwufetch when?

### ISSUE THREAD

**Issue by Twig6943** [TheDarkBug/uwufetch#238]
title

**Comment by TheDarkBug** [comment]
could you elaborate further?

**Comment by Twig6943** [comment]
.https://github.com/TheDarkBug/uwufetch

**Comment by TheDarkBug** [comment]
Well I think `uwufetch` is already fast, but if you want it to run even faster, you can use the `-r` option to use the cache.

**Comment by TheDarkBug** [comment]
Closed due to inactivity
