### ISSUE TITLE
Syntax error and Exec format error when ran

### ISSUE THREAD

**Issue by ASDownloadingAccount** [TheDarkBug/uwufetch#244]
I encounter a "Syntax error: "(" unexpected" error with sudo and "Exec format error" without sudo.
The Pi is running Raspbian version 9.8 and the Pi tried to run on is the Pi Zero W. The version attempted to run is the latest version as of writing.

**Comment by TheDarkBug** [comment]
Could you try to run the code in the [libfetch-rewire](https://github.com/TheDarkBug/uwufetch/tree/libfetch-rewrite) branch?

**Comment by TheDarkBug** [comment]
Closing because there was no answer

**Comment by ASDownloadingAccount** [comment]
> Closing because there was no answer

Sorry for the late answer, but I built the code from the clone and it worked. I haven't done it  from the Development branch anymore, but the issue was fixed anyway.

**Comment by TheDarkBug** [comment]
Oh ok, no problem
