### ISSUE TITLE
Ignoring Return Value of 'fscanf'

### ISSUE THREAD

**Issue by creepinson** [TheDarkBug/uwufetch#27]
So I ran make on my vps and got the following errors. I'm not sure how to remove this warning though.

```
uwufetch.c:101:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(file[1], "%d", &dnf);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
uwufetch.c:102:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(file[2], "%d", &emerge);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
uwufetch.c:103:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(file[3], "%d", &flatpak);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
uwufetch.c:104:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(file[4], "%d", &nix);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
uwufetch.c:105:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(file[5], "%d", &pacman);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
uwufetch.c:106:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(file[6], "%d", &rpm);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
uwufetch.c:107:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(file[7], "%d", &xbps);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
uwufetch.c: In function ‘get_info’:
uwufetch.c:148:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(fos_rel,"%[^\n]", version_name);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
uwufetch.c:165:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(fcpu, "%[^\n]", cpu_model);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
uwufetch.c:170:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(whoami, "%s", user);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
uwufetch.c:173:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(fcpu, "%[^\n]", cpu_model);
```

**Comment by TheDarkBug** [comment]
When i compile, i don't get this warning, can you tell me your gcc version?
Anyway this is only a warning, so uwufetch should work without problems.

**Comment by TheDarkBug** [comment]
The last commit removes some of the `fscanf()`, could you check if it now compiles without warnings?

**Comment by sethnine** [comment]
I am getting the similar warnings and after installing from source
[errorfile.txt](https://github.com/TheDarkBug/uwufetch/files/6135015/errorfile.txt)
I'm on pop_os using gcc version: 10.2.0 (Ubuntu 10.2.0-13ubuntu1)

**Comment by TheDarkBug** [comment]
> I am getting the similar warnings and after installing from source [errorfile.txt](https://github.com/TheDarkBug/uwufetch/files/6135015/errorfile.txt)

I'll try to completely rewrite the [pkgman()](https://github.com/TheDarkBug/uwufetch/blob/a9f7bcf41979e95cbbb78a7d8fc827daa0ceb949/uwufetch.c#L85) function without fscanf()

> I'm on pop_os using gcc version: 10.2.0 (Ubuntu 10.2.0-13ubuntu1)

The gcc version might be the problem, with gcc 11.1.0 i get no warnings.

**Comment by Guaxinim5573** [comment]
I'm with gcc 10.2.0 and get no warnings.
Arch Linux.
[gcc -vt.txt](https://github.com/TheDarkBug/uwufetch/files/6135825/gcc.-v.output.txt)

**Comment by TheDarkBug** [comment]
With some googling, I found that this warning exists because ignoring error handling for fscanf could lead to serious errors, so adding some error handling should fix it. Let me know if it shows fixed.

**Comment by sethnine** [comment]
after running make build:

gcc -O3 -o uwufetch uwufetch.c
uwufetch.c: In function ‘get_info’:
uwufetch.c:173:4: warning: ignoring return value of ‘fscanf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  173 |    fscanf(whoami, "%s", user);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~

and sudo make install gives no warnings/ errors

cp uwufetch /usr/bin/uwufetch
ls /usr/lib/uwufetch/ 2> /dev/null || mkdir /usr/lib/uwufetch/
cp res/* /usr/lib/uwufetch/
