### ISSUE TITLE
Unable to detect voidlinux automatically

### ISSUE THREAD

**Issue by CosmosAtlas** [TheDarkBug/uwufetch#31]
I have recent installation of voidlinux and `uwufetch` is unable to automatically identify the os information.

I checked `/etc/os-release` file and the issue seems to be here.

Void linux's `/etc/os-release` file have quotes around *void*:

```
# default /etc/os-release for voidlinux

NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"
```

After removing the quotes, i.e., now `NAME=void`, etc. `uwufetch` correctly detects the os and displays correctly.

While modifying the `/etc/os-release` file fixes the issue on the user side for `uwufetch`. It would be nice if the script can do it correctly. For example, both `pfetch` and `neofetch` have no problem detecting voidlinux in either `/etc/os-release` files with or without the quotes.

**Comment by TheDarkBug** [comment]
That's because the string after `ID=` starts with the ", like manjaro-arm, so adding the "" in to the string `void` should fix it.
