### ISSUE TITLE
*FEATURE REQUEST * GPU

### ISSUE THREAD

**Issue by Joe-Todd0** [TheDarkBug/uwufetch#35]
I am sorry if this is the wrong place to put this but i couldn't find any place else to do so.

I do not currently have the time to add this but something that may help, all someone needs to do is find a way to print it correctly i think. From my findings, there is no standard way to get the GPU name so the way i did it was to use glxinfo and opengl, the command is -> glxinfo | grep 'OpenGL renderer string:' | sed 's/^.*: //' | cut -f1 -d\"(\"

i might be completely wrong but i think this might be your best bet in grabbing the GPU data (probs am  wrong tho xD)

**Comment by Joe-Todd0** [comment]
additionally, i believe that on github now you can open up discussions on repos? that might be a good idea so people can put in feature requests in the correct place :D

**Comment by TheDarkBug** [comment]
I'm already working on it, your solution works sometimes, in my case the command output is `AMD Radeon`, because the complete name is `AMD Radeon(TM) Vega 8 Graphics (RAVEN, DRM 3.40.0, 5.11.6-zen1-1-zen, LLVM 11.1.0)`, so the output will stop to the first `(`. I'm currently trying with `lspci -mm`.

**Comment by Joe-Todd0** [comment]
yeah i should have mentioned that haha. If you would like any help with it or anything feel free to shoot me a message on discord or on here :)

Discord: pink#7915

**Comment by Guaxinim5573** [comment]
I also was working on it, but I had no time.
My solution was using `lspci -mm` too.
`lspci -mm | grep "VGA\|00:02" | cut --fields=4,6 -d '"' --output-delimiter=" " | sed "s/ Controller.*//"`
returns:
`Intel Corporation 2nd Generation Core Processor Family Integrated Graphics`
But I can't test in others Linux distros or different GPU.

**Comment by TheDarkBug** [comment]
> But I can't test in others Linux distros or different GPU.

I just tried, it works!
Thanks man, would you send a PR?

**Comment by Guaxinim5573** [comment]
Of course! I'm making one.
