### ISSUE TITLE
CPU name gets cut off & GPU name too long

### ISSUE THREAD

**Issue by chfour** [TheDarkBug/uwufetch#39]
This is what happens when I run it:

![2021-03-15_15-03-56](https://user-images.githubusercontent.com/44905638/111166413-5c049d80-85a0-11eb-99cd-081ce02f17b2.png)

The CPU model name gets weirdly cut off to just two characters and the GPU model wraps over to the next line, breaking the ASCII art on the left. Font is Terminus and I'm using Konsole if that helps

**Comment by TheDarkBug** [comment]
The issue is caused by `/proc/cpuinfo` and `lspci` could you please send the output of `cat /proc/cpuinfo` and `lspci -mm`?

**Comment by chfour** [comment]
Sure! https://pastebin.com/zFMWs142

**Comment by TheDarkBug** [comment]
In the last 2/3 commits i tried to fix this issues, but now to get gpu info you need   [lshw](https://github.com/lyonel/lshw).

**Comment by chfour** [comment]
So I installed lshw, and while the CPU model name works fine now, the GPU model still wraps around to the next line. 
![2021-03-16_09-43-23](https://user-images.githubusercontent.com/44905638/111283470-75a8f200-863f-11eb-933c-78dbf0bab75d.png)
Neofetch solves this issue by truncating the text:
![2021-03-16_10-10-44](https://user-images.githubusercontent.com/44905638/111284057-0c75ae80-8640-11eb-8b7a-a2a8c4e37d02.png)
I would implement this, however my knowledge of C is basically next to nothing. :P

**Comment by TheDarkBug** [comment]
Neofetch solution is good, I will implement a similar solution
