### ISSUE TITLE
Shell name gets cut off for certain shells

### ISSUE THREAD

**Issue by LukeHuckman** [TheDarkBug/uwufetch#42]
I've only tested this with bash, but I have a feeling this happens on other 4-letter shells as well since this doesn't happen with zsh.

![image](https://user-images.githubusercontent.com/45264354/111333306-86904c80-86ad-11eb-97dd-77cfbe6aa1b7.png)

**Comment by TheDarkBug** [comment]
That's because I wanted to write only the name of the shell, not it's full path. But as I can see this works only with zsh
