### ISSUE TITLE
Modified Gentoo Logo in Gentoo's Artwork Project

### ISSUE THREAD

**Issue by xgqt** [TheDarkBug/uwufetch#46]
I propose to add the modified Gentoo logo to the Gentoo Artwork project.
https://github.com/TheDarkBug/uwufetch/blob/main/res/gentoo.png

In order to make this happen a "bug" will have to be filed to the Gentoo bugsystem - https://bugs.gentoo.org/enter_bug.cgi?format=guided

More about the Gentoo's Artwork Project:
- https://wiki.gentoo.org/wiki/Project:Artwork
- https://wiki.gentoo.org/wiki/Project:Artwork/Artwork

**Comment by xgqt** [comment]
Don't treat this like a warning or something ;D
Just thought that could be a good way to show off your artwork.

**Comment by TheDarkBug** [comment]
That's a good idea, but i am not the original artist. You can find more info in [IMAGES.md](https://github.com/TheDarkBug/uwufetch/blob/main/res/IMAGES.md#credits).

**Comment by xgqt** [comment]
> That's a good idea, but i am not the original artist. You can find more info in [IMAGES.md](https://github.com/TheDarkBug/uwufetch/blob/main/res/IMAGES.md#credits).

would you ping the creator? I dont have a reddit acct

**Comment by TheDarkBug** [comment]
Of course, I'll let you know

**Comment by xgqt** [comment]
@TheDarkBug update on this?

**Comment by TheDarkBug** [comment]
I contacted him 3d ago, I have no reply yet

**Comment by TheSatisfiedPig** [comment]
My apologies for the late reply.
What should I do?

**Comment by xgqt** [comment]
> My apologies for the late reply.
> What should I do?

Great that you are here.

I didn't find any documentation on how to approach the problem of adding new artwork into Gentoo so I think the only way is to send a mail at artwork@gentoo.org and start the discussion.

**Comment by aliceinwire** [comment]
Hello everyone, I'm alicef member of Gentoo Artwork.
I'll support support importing the Genchu image to Gentoo artwork.
For importing it, clear license statement is needed.
@TheSatisfiedPig Could you let me know the license of the image?

**Comment by TheSatisfiedPig** [comment]
As original Gentoo logo, Genchu logo license is also CC-BY-SA/2.5.
https://wiki.gentoo.org/wiki/Project:Artwork/Artwork

**Comment by aliceinwire** [comment]
Thanks, I will open a bug to Gentoo Trustee.

**Comment by aliceinwire** [comment]
bug number [#777969 ](https://bugs.gentoo.org/777969)

**Comment by xgqt** [comment]
UwU
https://twitter.com/gentoo/status/1377479774688268292

**Comment by genchu** [comment]
@xgqt UwU chu!

**Comment by xgqt** [comment]
Closing. 
Logo was accepted to the Gentoo project.

Thanks for great art to @TheSatisfiedPig .
Thanks for showcasing it in uwufetch to the uwufetch devs, namely @TheDarkBug .
Thanks for Gentoo developers' support to @aliceinwire .
