### ISSUE TITLE
Fallback approach of getting GPU info stopped working

### ISSUE THREAD

**Issue by LukeHuckman** [TheDarkBug/uwufetch#47]
I noticed that GPU detection without `lshw` stopped working completely after #45.

Here's the output I get before the merge:
![Screenshot from 2021-03-19 22-45-26](https://user-images.githubusercontent.com/45264354/111798219-d4eb5880-8904-11eb-975a-d68eec0cd5e5.png)

And here's after the merge:
![Screenshot from 2021-03-19 22-41-22](https://user-images.githubusercontent.com/45264354/111797966-92c21700-8904-11eb-9695-9f745f841f10.png)

I was wondering if this is intentional, since these lines still exist:
https://github.com/TheDarkBug/uwufetch/blob/57e016e3dcae0301b5c257530ca1a65f9c3cb885/uwufetch.c#L219-L223
Which as far as I can understand is the fallback GPU detection if `lshw` isn't installed. Correct me if I'm wrong though.

**Comment by LukeHuckman** [comment]
If it *is* intentional, I'll have to change `lshw` on the AUR from an optional to a required dependency.

**Comment by TheDarkBug** [comment]
The lines are still in the file to prevent errors if lshw is missing, so there's something wrong in the code. Maybe it has something to do with the `gpu_model` being an array, but I'm not sure.

**Comment by TheDarkBug** [comment]
Just solved: the `gpu_model[0]` (line 219) somehow had 1 char, so the condition was false and the `if` was never happening.
