### ISSUE TITLE
Incorrect GPU name if lshw is not present, text too long

### ISSUE THREAD

**Issue by workonfire** [TheDarkBug/uwufetch#54]
Hi.

![Screenshot](https://i.imgur.com/5HbtOcn.png)

As far as I can see, this is a duplicate of #39, but [this commit](https://github.com/TheDarkBug/uwufetch/commit/117dfe96dd55ba809bcdce90f5595fb044569be3) **did not** resolve the issue.

I think this may be caused by `lshw` being not installed, hence the GPU name is being detected incorrectly as well (I have a NVIDIA GPU).

**Comment by TheDarkBug** [comment]
The gpu that it detects should be the one integrated in the cpu, I tried with [the last commit](https://github.com/TheDarkBug/uwufetch/commit/383abb2aa0d5e29e8f8b29aaf082da08b60f19e7) on a pc with nvidia and intel graphics cards and it worked, I hope it works also for you.
