### ISSUE TITLE
Tracking image license & copyrights

### ISSUE THREAD

**Issue by robbat2** [TheDarkBug/uwufetch#55]
Issue #46 raised the question of license and copyright attribution for the Gentoo image, but I don't see any records for other artwork in this project.

The top-level LICENSE file says GPL-3, but that isn't accurate.

Please add a `COPYRIGHT` file that tracks, for each externally contributed image:
- Copyright holder(s) of individual artwork
- License of individual artwork
- Reference on the holders & license
- Additional data to satisfy requirements of individual licenses, e.g. CC licenses require marking about derivatives: https://wiki.creativecommons.org/wiki/License_Versions#Modifications_and_adaptations_must_be_marked_as_such

I've tried to build an example using Android for  you:

# Android
## Base artwork:
- Copyright Holder: Google Inc.
- License: CC-BY-3.0 
- License-URL: https://creativecommons.org/licenses/by/3.0/
- Reference: https://developer.android.com/distribute/marketing-tools/brand-guidelines#android_robot
## Modifications
- Description: uwu style
- Copyright Holder: ???
- License: CC-BY-3.0 
- License-URL: https://creativecommons.org/licenses/by/3.0/

**Comment by TheDarkBug** [comment]
Ok I'll make a file that contains all the copyright things, but I know very little about copyright and law, so it will take a very long time (at least for me). Also in this period I am too busy with school, so I can't make it right now. Thanks for the suggestion.

**Comment by robbat2** [comment]
This is mostly just tracking the holder and license for all of the images. If you get started on the template, then you can probably require it as information when new images are submitted
