### ISSUE TITLE
Wrong Ram usage

### ISSUE THREAD

**Issue by JanzenJohn** [TheDarkBug/uwufetch#59]
My Ram usage is off by 5gb

~3gb real usage
but 8gb displayed in uwufetch

Running 5.11.10-artix1-1 64bit
![Image](https://user-images.githubusercontent.com/51709412/113284658-785f4480-92d9-11eb-8be3-97edeb827603.png)

**Comment by TheDarkBug** [comment]
I tried some fixes to this issue (in 79f5085 and 688c654), but not even one of them worked. I could solve this by using the `free` shell command.

**Comment by Guaxinim5573** [comment]
Never realized but I have the same issue.
![image](https://user-images.githubusercontent.com/49736632/113351237-f4c14a00-9310-11eb-9bbd-d63c11485ae2.png)
Using code from last commit.

**Comment by TheDarkBug** [comment]
Fixed in c67bcdc (#60)
