### ISSUE TITLE
0 ram usage

### ISSUE THREAD

**Issue by JanzenJohn** [TheDarkBug/uwufetch#61]
It's me with the ram again

After building uwufetch new a new RAM issue came up now I have 0 / 0 MB RAM usage
![Image](https://user-images.githubusercontent.com/51709412/113506558-169b1680-9535-11eb-861f-70f3b06d0f66.png)

**Comment by TheDarkBug** [comment]
As I was expecting, here is another ram issue. Could you send the output of `free` and `free 2> /dev/null`?

**Comment by Guaxinim5573** [comment]
I have the same issue.
![image](https://user-images.githubusercontent.com/49736632/113522224-3f430080-9575-11eb-99f0-15a5e3dc9752.png)

`free` output:
```
               total        used        free      shared  buff/cache   available
Mem.:        3458764     1355592      119012      166864     1984160     1707764
Swap:         460796         780      460016
```
`free 2> /dev/null` output (same as `free` output):
```
               total        used        free      shared  buff/cache   available
Mem.:        3458764     1355844      118760      166864     1984160     1707512
Swap:         460796         780      460016
```
