### ISSUE TITLE
[FEATURE-REQUEST] Man pages

### ISSUE THREAD

**Issue by Guaxinim5573** [TheDarkBug/uwufetch#68]
A good way to show instructions and some information is in man pages, this is something missing in `uwufetch`.
The man page could contain some info from README.md (like requisites, LICENSE, image and copyright info).

Man pages can be developed in a lot of different ways, just searching on internet and choose the one you think it's the better.

**Comment by TheDarkBug** [comment]
Yes, a man page could be useful is someone wants some info without going on the README, I'm working on it (will take some time, I never wrote man pages).

**Comment by Guaxinim5573** [comment]
I think FEATURE-REQUEST issues should be opened until someone make the request or completely reject it, so if someone open issues tab he can see this requests and make a PR if he wants.

**Comment by TheDarkBug** [comment]
No problem, lol
