### ISSUE TITLE
[Feature Request] Config file

### ISSUE THREAD

**Issue by LukeHuckman** [TheDarkBug/uwufetch#69]
This might be too soon to implement this, but it might be a good idea for uwufetch to generate a config file to be edited and then read when the command is run so that you don't have to enter arguments every time, i.e. setting default behaviours. 

Doing this can also simplify things later down the line if more features are added.

**Comment by TheDarkBug** [comment]
That's a good one, specially if someone uses his own custom image. Tomorrow I'll start working on it, I thought to put the config file in `$HOME/.config/uwufetch/config`. Also this is the 69th issue, nice.

**Comment by Guaxinim5573** [comment]
I started working on it some hours ago and did progress but still have a few bugs and there is nothing to check for syntax errors.
It's in [Guaxinim5573/uwufetch](https://github.com/Guaxinim5573/uwufetch).
Currently it reads a `config` file in the project directory.

**Comment by TheDarkBug** [comment]
Nice, maybe I'll try to solve some of the bugs, if you can't fix them

**Comment by TheDarkBug** [comment]
> It's in [Guaxinim5573/uwufetch](https://github.com/Guaxinim5573/uwufetch).

I merged it to the main branch and used sscanf to read info.

> I started working on it some hours ago and did progress but still have a few bugs and there is nothing to check for syntax errors.

I fixed the comments, but there is still no error checking.

@LukeHuckman we added image and distro name to the config options, do you have any suggestions on other customization?

**Comment by LukeHuckman** [comment]
Perhaps some toggles to enable/disable some of the printed system info itself? Or even an option display the RAM in another unit (e.g. GB/GiB)?

A toggle to colourise the system info to match the ASCII art would also be a nice touch.

Though, these will require some tweaking to the main code itself.

**Comment by TheDarkBug** [comment]
I'll try all of them, but right now I am working on customizing the output. Maybe in future I'll add the option to customize the command to show the image.

**Comment by TheDarkBug** [comment]
> Perhaps some toggles to enable/disable some of the printed system info itself?

Done!

> Or even an option display the RAM in another unit (e.g. GB/GiB)?

To make something like this I should edit the command to get ram, then re-execute it, but to do that there should be a `get_ram()` or something, which would just make the code more confusing than it is right now.

> Maybe an option to display CPU speed?

Should be kinda easy, but if it is printed after the `cpu_name`, (in my case) it would be removed for being too long.

> A toggle to colourise the system info to match the ASCII art would also be a nice touch.

Could be done by storing colors in a struct instead of using macros.

Anyway the original request was satisfied in c403d0a, e877e3c and 313a5a4, so I am closing this issue.
