### ISSUE TITLE
too much space between cpuwu and cpuwu name

### ISSUE THREAD

**Issue by zcake3000** [TheDarkBug/uwufetch#7]
too much space between cpuwu and cpuwu name
![2021-03-07_01-32](https://user-images.githubusercontent.com/70055899/110215623-c6a14380-7ee5-11eb-8f6d-58f1a6695d15.png)

**Comment by TheDarkBug** [comment]
I don't know why is this happening, anyway i am currently working on a new printing system (to allow using images instead of ascii art), which should also prevent this kind of errors.

**Comment by TheDarkBug** [comment]
Ok it may be at lines 44/47, because i remove the spaces in c, and not in bash, so i should use `sed` to remove the useless spaces. I'll soon push an update.
