### ISSUE TITLE
[BUG] Segmentation fault if optimization is enabled

### ISSUE THREAD

**Issue by TheDarkBug** [TheDarkBug/uwufetch#71]
Ok it's a little awkward to submit an issue to my own program.
Anyway if `uwufetch` is compiled with `-O3` or any other optimization it runs with a segmentation fault:

![image](https://user-images.githubusercontent.com/41623496/114698430-60e37b00-9d1f-11eb-9062-4b6b541c7431.png)

I don't know why is this happening, maybe it has something to do with parsing the config file.

**Comment by Guaxinim5573** [comment]
This error is happening on [line 262](https://github.com/TheDarkBug/uwufetch/blob/879c56ef7a920409e7aa41104ac19b4772b7514c/uwufetch.c#L262).

**Comment by TheDarkBug** [comment]
You are right, in my case the variable doesn't store anything (it should be the processor architecture), could you tell me if in your case is has some value? If for some reasons it is useless I'll remove it.

**Comment by Guaxinim5573** [comment]
Yes, for me it has a value, it's `x86_64`.
