### ISSUE TITLE
uwufetch under macOS

### ISSUE THREAD

**Issue by sech1p** [TheDarkBug/uwufetch#81]
0 packages under macOS: https://github.com/TheDarkBug/uwufetch/pull/76#issue-616358491
~~macOS returns illegal hardware instruction: https://github.com/TheDarkBug/uwufetch/commit/938520b4f39a52aaa9734028478660221e7bdeeb~~

**Comment by TheDarkBug** [comment]
I just installed homebrew on arch linux and it works, could you send the output of `brew list --formulae` and `brew list --formulae 2> /dev/null | wc -l`?

**Comment by sech1p** [comment]
> I just installed homebrew on arch linux and it works, could you send the output of `brew list --formulae` and `brew list --formulae 2> /dev/null | wc -l`?

`brew list --formulae`:
```shell
adwaita-icon-theme		libvidstab
aom				libvorbis
atk				libvpx
babel				libvterm
bash				libx11
bdw-gc				libxau
berkeley-db			libxcb
bison				libxdmcp
byacc				libxext
c-ares				libxmu
cabextract			libxrender
cairo				libxt
cloc				links
cmake				little-cms2
coreutils			lolcat
(and a lot of other packages...)
```

`brew list --formulae 2> /dev/null | wc -l`:
```shell
     214
```

**Comment by TheDarkBug** [comment]
The command gives output, so it is not the problem. I should test it on a Mac, but I have not a Mac.

**Comment by sech1p** [comment]
update

**Comment by TheDarkBug** [comment]
I'm sorry that apparently no one uses a Mac, I would try to use [darling](https://github.com/darlinghq/darling) but I can't build it, so I'll try to install Mac os in a virtual machine (if it is legal)

**Comment by TheDarkBug** [comment]
Should be fixed with #98

**Comment by TheDarkBug** [comment]
> It returns me `32767` (max value of 16-bit integer) packages, however, I had only 232 👀

Status update for [issues](https://github.com/TheDarkBug/uwufetch/pull/98#issuecomment-845705790) in #98

**Comment by voidStellar14** [comment]
I have been trying to install uwufetch on my MacBook (running MacOS X Big Sur) and have been having issues on the "sudo make install" step.

Here is the error and make debug:

sudo make install
cc -O3 -o uwufetch uwufetch.c
pandoc uwufetch_man.md -st man -o uwufetch.1
uwufetch.1.gz already exists -- do you wish to overwrite (y or n)? y
cp uwufetch /usr/bin/uwufetch
cp: /usr/bin/uwufetch: Operation not permitted
make: *** [install] Error 1

make debug

cc -Wall -Wextra -o uwufetch uwufetch.c
ld: can't write output file: uwufetch for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [debug] Error 1

I have tried a restart, a sudo rm -rf ~/uwufetch, and deleting the directory via a file manager.
none of those have worked

Is there a way to fix this error?

**Comment by TheDarkBug** [comment]
Apparently `/usr/bin/` is not accessible by the user, so the programs should be installed in `/usr/local/bin/`.
As soon as I can I will create a new makefile target to correctly install in Mac os.

**Comment by voidStellar14** [comment]
Thanks!

**Comment by TheDarkBug** [comment]
I just updated the makefile, `sudo make install` should now work

**Comment by voidStellar14** [comment]
it works, but it looks like this
![Screen Shot 2021-06-06 at 7 54 33 PM](https://user-images.githubusercontent.com/80975993/120944280-b164cc80-c701-11eb-8a82-6a7d9d8605d0.png)

**Comment by voidStellar14** [comment]
This is what it is supposed to look like ![Screenshot_20210606-200234.png](https://user-images.githubusercontent.com/80975993/120944428-68f9de80-c702-11eb-99ef-a2a8b3965bc0.png)
