### ISSUE TITLE
Termux issue: fatal error: 'json-c/json.h' file not found

### ISSUE THREAD

**Issue by voidStellar14** [TheDarkBug/uwufetch#82]
![Screenshot_20210421-121849.png](https://user-images.githubusercontent.com/80975993/115588541-dd84d500-a29c-11eb-82f3-cbdebc1c347c.png)

**Comment by LukeHuckman** [comment]
It appears that `json-c` is now a required dependency for uwufetch to work.
Try installing it with `pkg install json-c` and see if the problem is resolved

**Comment by TheDarkBug** [comment]
In my case installing `json-c` worked, just like in arch Linux. In the aur `json-c` is already a required package, if I didn't write wrong options.

**Comment by voidStellar14** [comment]
Thanks, that solved the issue

**Comment by TheDarkBug** [comment]
Fixed by removing json-c in [1.4](https://github.com/TheDarkBug/uwufetch/tree/1.4)
