### ISSUE TITLE
Why use json to a config file?

### ISSUE THREAD

**Issue by Guaxinim5573** [TheDarkBug/uwufetch#83]
**This is a discussion, not an actual issue.**

Recently, UwUFetch started using JSON for the config file using an external library, but I think JSON isn't good for a config file a human would write. Here is why:
1. JSON isn't very readable for humans.
2. It can cause more syntax errors.
3. A config file should be easy to understand and write, without many rules.
4. Need an external library

I think the old approach using a simple `KEY=VALUE` was better than a JSON file. Here is why:
1. More readable for humans.
2. It's simple to write, so there are not many syntax errors.
3. A custom parser isn't hard to make, no need to use an external library.

EDIT: Spelling errors.

**Comment by TheDarkBug** [comment]
The problems caused by the external library are enough to revert, I'm rebuilding the config parser.

**Comment by TheDarkBug** [comment]
Now using custom parser (09b32b1), I'll soon publish a new release

**Comment by TheDarkBug** [comment]
I just released [1.4](https://github.com/TheDarkBug/uwufetch/tree/1.4), so this issue and #82 are fixed
