### ISSUE TITLE
man page: incorrect heading alignment ("OPTIONS")

### ISSUE THREAD

**Issue by thetayloredman** [TheDarkBug/uwufetch#88]
`OPTIONS` is *never* a child of `SYNOPSYS`.

`man` renders currently as:

```
SYNOPSIS
       uwufetch [OPTIONS] [ARGUMENTS]
   OPTIONS
```

where it should be

```
SYNOPSIS
       uwufetch [OPTIONS] [ARGUMENTS]

OPTIONS
```

**Comment by TheDarkBug** [comment]
The "#" in that line should be removed, right now I can't access my computer, so I will do it tomorrow (or you can send a PR)
