### ISSUE TITLE
uwufetch doesnt recognize Endeavour OS, even though the page says that it is fully supported

### ISSUE THREAD

**Issue by voidStellar14** [TheDarkBug/uwufetch#89]
I have read the read me today, and saw that uwufetch supports endeavour os. i clean installed uwufetch and it still says "unknown" in OWOS and shows a tux for my distro ascii. How can i fix this?

![void uwufetch on eos not working lol](https://user-images.githubusercontent.com/80975993/116798006-801d2f00-aab9-11eb-8199-11ce6ba86480.png)

**Comment by Guaxinim5573** [comment]
Cat you send the output of `cat /etc/os-release`?

**Comment by prettykool** [comment]
I booted up an ISO of the latest version of EndeavourOS(2021.04.17), and found that it worked on my end. I'll include a screencap of it, alongside the `cat /etc/os-release` command, as per the suggestion of @Guaxinim5573. If there's any differences between my output and yours, let us know.

![image](https://user-images.githubusercontent.com/79608594/116828058-fd03e380-ab61-11eb-81eb-cb62dbb7ac48.png)

**Comment by Guaxinim5573** [comment]
Maybe the output of `cat /etc/os-release` was different in older versions of EndeavourOS.
If it works for you now, close the issue. 

If you still use a old version of EndeavourOS, send the output of `cat /etc/os-release` in the old version.

**Comment by TheDarkBug** [comment]
If the name in your version of endeavouros is different, put it [here](https://github.com/TheDarkBug/uwufetch/blob/df74337b287fedbdccf5b27482ef2b64750ec31d/uwufetch.c#L587) and send a PR

**Comment by voidStellar14** [comment]
> Cat you send the output of `cat /etc/os-release`?

The name is EndeavourOS and not endeavouros according to the command

**Comment by voidStellar14** [comment]
> Cat you send the output of `cat /etc/os-release`?

![endeavour cat os and uwufetch](https://user-images.githubusercontent.com/80975993/116946436-9d90fb00-ac69-11eb-8d13-81f4314d1acb.png)
here is the image of the cat /etc/os-release and uwufetch

**Comment by voidStellar14** [comment]
> If the name in your version of endeavouros is different, put it [here](https://github.com/TheDarkBug/uwufetch/blob/df74337b287fedbdccf5b27482ef2b64750ec31d/uwufetch.c#L587) and send a PR

I do not know if capitalization plays a role, it works for @Guaxinim5573 and we seem to have the same information except for the build ID being a few months older than his.

**Comment by prettykool** [comment]
> I do not know if capitalization plays a role, it works for @Guaxinim5573 and we seem to have the same information except for the build ID being a few months older than his.
I wrote a quick patch to test this out. Try and see if it works on your end.
[E_OS_capitalization.zip](https://github.com/TheDarkBug/uwufetch/files/6423546/E_OS_capitalization.zip)

**Comment by voidStellar14** [comment]
> > I do not know if capitalization plays a role, it works for @Guaxinim5573 and we seem to have the same information except for the build ID being a few months older than his.
> 
> I wrote a quick patch to test this out. Try and see if it works on your end.
> [E_OS_capitalization.zip](https://github.com/TheDarkBug/uwufetch/files/6423546/E_OS_capitalization.zip)
> 

How do I use it? Do i just download the zip and replace the original with it?

**Comment by prettykool** [comment]
> > > I do not know if capitalization plays a role, it works for @Guaxinim5573 and we seem to have the same information except for the build ID being a few months older than his.
> > 
> > 
> > I wrote a quick patch to test this out. Try and see if it works on your end.
> > [E_OS_capitalization.zip](https://github.com/TheDarkBug/uwufetch/files/6423546/E_OS_capitalization.zip)
> 
> How do I use it? Do i just download the zip and replace the original with it?

Unzip it, move the `E_OS_capitalization.patch` file to the `uwufetch` directory, and use `git apply E_OS_capitalization.patch` to make the changes to `uwufetch.c`.

**Comment by voidStellar14** [comment]
> > > > I do not know if capitalization plays a role, it works for @Guaxinim5573 and we seem to have the same information except for the build ID being a few months older than his.
> > > 
> > > 
> > > I wrote a quick patch to test this out. Try and see if it works on your end.
> > > [E_OS_capitalization.zip](https://github.com/TheDarkBug/uwufetch/files/6423546/E_OS_capitalization.zip)
> > 
> > 
> > How do I use it? Do i just download the zip and replace the original with it?
> 
> Unzip it, move the `E_OS_capitalization.patch` file to the `uwufetch` directory, and use `git apply E_OS_capitalization.patch` to make the changes to `uwufetch.c`.

I'm super dumb and don't know how to lol

**Comment by prettykool** [comment]
> I'm super dumb and don't know how to lol

```sh
#!/bin/bash

# For you, my dearly beloved.
# This script will do all the work for you, as
# long as you make sure its privileges set to 
# chmod 757

# Clone uwufetch from the repo.
git clone https://github.com/TheDarkBug/uwufetch/

# Switch to the directory.
cd uwufetch

# Retrive the patch.
wget https://github.com/TheDarkBug/uwufetch/files/6423546/E_OS_capitalization.zip
unzip E_OS_capitalization.zip

# Apply the patch.
git apply E_OS_capitalization.patch

# Build uwufetch from source
make
sudo make install

# That's all.```

**Comment by voidStellar14** [comment]
Thanks, I'll try it tonight!

**Comment by voidStellar14** [comment]
the patch worked even though it gave 2 errors. Thank you very much everyone! have a nice day!

**Comment by voidStellar14** [comment]
![all of the fetches are working pog](https://user-images.githubusercontent.com/80975993/117347771-727bf680-ae77-11eb-8b08-2c7a0d9368aa.png)
