### ISSUE TITLE
Package counter doesn't distinguish between native and Flatpak packages

### ISSUE THREAD

**Issue by LukeHuckman** [TheDarkBug/uwufetch#9]
Here's a picture of what I mean:
![Screenshot from 2021-03-07 05-16-16](https://user-images.githubusercontent.com/45264354/110221002-830a0200-7f04-11eb-8bfc-694bf624eb13.png)
As you can see, the 14 Flatpak packages gets included in the (pacman) package count, which is incorrect.

**Comment by LukeHuckman** [comment]
I think it has something to do with how the package count and package manager name are determined here:
https://github.com/TheDarkBug/uwufetch/blob/ae8ec0c57e1964875300e58534c61a2c9cfb12d8/uwufetch.c#L110
https://github.com/TheDarkBug/uwufetch/blob/ae8ec0c57e1964875300e58534c61a2c9cfb12d8/uwufetch.c#L64-L73
Which totals up all the packages from different package managers and then passes the value to `print_info()`.
And how `print_info()` handles it:
https://github.com/TheDarkBug/uwufetch/blob/ae8ec0c57e1964875300e58534c61a2c9cfb12d8/uwufetch.c#L83
Which pretty much makes it print only one package manager even if there are more than one.

**Comment by TheDarkBug** [comment]
I replaced `snprintf()` with `strcat()`, so the string will be concatenated to the previous value, but the package count is still the total. Maybe in future I'll add the option to customize the output of packages.
