### ISSUE TITLE
.config/uwufetch/config dosent appear

### ISSUE THREAD

**Issue by KenwoodFox** [TheDarkBug/uwufetch#99]
Maybe im just having trouble finding the docs but im trying to get images to work, i installed `vio` but i cant find a config file and another issue mentioned that a config file would be placed under ~/.config/uwufetch/config ?

**Comment by TheDarkBug** [comment]
> Maybe im just having trouble finding the docs but im trying to get images to work, i installed `vio`

To use images you need `viu`, not `vio`, you can install it through the [aur](https://aur.archlinux.org/packages/viu-git/) or through the [github repo](https://github.com/atanunq/viu), as mentioned in the [readme](https://github.com/TheDarkBug/uwufetch#how-to-use-images).

> but i cant find a config file and another issue mentioned that a config file would be placed under ~/.config/uwufetch/config ?

The config file is not created by `uwufetch`, if you want it you need to create it (in ~/.config/uwufetch/config or in a custom directory).
For more info about the configuration and anything else, type `man uwufetch` in the terminal.

**Comment by KenwoodFox** [comment]
Thanks so much for that. I did find everything under `man`. Now i just gotta fix the resolution 
![image](https://user-images.githubusercontent.com/31870999/120836753-e8858300-c533-11eb-9e91-570da0efbd01.png)

**Comment by chfour** [comment]
Hey, quick heads-up: the "resolution" issue is caused by Konsole (I think that's what you're using) not supporting any image protocols (iterm and kitty). `viu` falls back to using the unicode half-block method. To fix that, you'd need to use a different terminal emulator.

**Comment by KenwoodFox** [comment]
> Hey, quick heads-up: the "resolution" issue is caused by Konsole (I think that's what you're using) not supporting any image protocols (iterm and kitty). `viu` falls back to using the unicode half-block method. To fix that, you'd need to use a different terminal emulator.

An entirely different terminal? Im using Yakuake in the screenshot. is there no way to make viu work in konsole/Yakuake?

**Comment by Guaxinim5573** [comment]
> An entirely different terminal? I'm using Yakuake in the screenshot. is there no way to make viu work in Konsole/Yakuake?

As far as I know, you can't display images in Konsole.

A quote from [viu](https://github.com/atanunq/viu) repository:
> It uses either [iTerm](https://iterm2.com/documentation-images.html) or [Kitty](https://sw.kovidgoyal.net/kitty/graphics-protocol.html) graphics protocol, if supported. If not, lower half blocks (▄ or \u2584) are displayed instead.

Probably, your terminal emulator doesn't support iTerm and Kitty protocol.

**Comment by chfour** [comment]
Yes, Konsole sadly doesn't support any of those (and Yakuake uses Konsole). If you really wanted this to work I guess you could use Kitty

**Comment by chfour** [comment]
You could always set `ascii=true` in your config or remove `viu`, that way uwufetch will print the default ascii logos

**Comment by KenwoodFox** [comment]
> You could always set `ascii=true` in your config or remove `viu`, that way uwufetch will print the default ascii logos

Thank you for the advice, i really appreciate having it all laid out like that. I understand now :3 I think ill stick with just the ascii then, i really enjoy konsole and i dont think id change it up rn.

**Comment by chfour** [comment]
I'm in pretty much the same situation. Glad I could still help!
